version: '3.2'

services:
    game_servers:
        # The name format for the pre-built images is "hercules:[server mode]-[packet version]",
        # e.g. to run a Renewal server on the latest packet version supported by Hercules, edit
        # this to instead be florianpiesche/hercules:renewal-latest.
        # If you want to run a local image you've built yourself, edit this to simply be the
        # tag for that image, e.g. simply "hercules".
        image: hercules-docker
        restart: on-failure       
        ports:
            # To make your game server accessible over the internet, you will need to forward
            # these ports to the IP address of the computer running the server. You do NOT need
            # to forward the port for the database server - doing so is insecure, and there is
            # login server
            - 6900:6900
            # character server
            - 6121:6121
            # map server
            - 5121:5121
        environment:
            # These variables will work for a default setup. Feel free to
            # edit their contents to your liking. Make sure to duplicate any
            # changes you make in the database service below.

            # This is just the host name and the port for the database server.
            # If you don't want to set up your own database server, simply
            # leave these as they are and your game servers will use the
            # database service defined below.
            MYSQL_SERVER: database
            MYSQL_PORT: 3306:3306

            # The user name and password to use for accessing the database.
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

            # The database to use for your data on the database server.
            MYSQL_DATABASE: ragnarok

            # The user name and password for the inter-server communication
            # account.
            INTERSERVER_USER: wisp
            INTERSERVER_PASSWORD: wisp

        # volumes:
        #     # Using volumes to store the configuration means
        #     # your Docker installation will keep the configuration
        #     # outside of the container - so even if you update
        #     # or destroy and rebuild the container, your configuration
        #     # will persist.
        #     - configuration:/app/hercules/conf/import
        #     - sql_init:/app/hercules/sql-files/

    # This service will cause Docker to also bring up a database service to
    # use with your Hercules servers. Having a separate container for this is useful
    # as the database will be separate from any other databases you may
    # be running, and also saves you having to set up a database server yourself.
    # Be sure to mirror any changes to the environment variables you make above
    # in the variables here!
    database:
        image: ubuntu/mysql
        restart: on-failure
        depends_on:
            - game_servers
        environment:
            # The password for the "root" (administrator) user on the database.
            # If you're not planning on doing anything that requires administrator
            # access to the database, you can comment this line out and the mariadb
            # image will generate a random password for the root user on first startup,
            # which is more secure than having a default one.
            # MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: yes

            # The user name and password to create for the Hercules servers
            # to connect to the database.
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

            # The database to create for the Hercules servers. This will be
            # automatically set up using the SQL files required for the initial
            # Ragnarok database for your selected server mode, as per Hercules
            # documentation.
            MYSQL_DATABASE: ragnarok

            # The user name and password for the inter-server communication
            # user Hercules uses.
            INTERSERVER_USER: wisp
            INTERSERVER_PASSWORD: wisp
        expose:
            # Rather than "ports" as for the game servers, we're using "expose" to specify
            # the port for the database service. This means the database will *only* be
            # accessible to other services in this compose file but not from the host
            # computer itself, which is more secure as only the game servers need
            # access to the database.
            - 3306:3306
        volumes:
            # Again, using a volume for the database data means that even if you
            # destroy and rebuild the database service, your database will remain.
            - mysql_data:/var/lib/mysql
            - sql_init:/docker-entrypoint-initdb.d

    phpmyadmin: 
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: localhost
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80

volumes:
    mysql_data:
    configuration:
    sql_init:
